title = "Social Force Model Config"

[scene]
enable_group = true  # 그룹 기능을 활성화하여 에이전트들이 그룹 단위로 행동할 수 있도록 합니다.
agent_radius = 0.5  # 에이전트의 반지름을 0.35m로 설정하여 에이전트의 크기를 정의합니다.
max_speed_multiplier = 1.3  # 에이전트의 최대 속도를 초기 원하는 속도의 1.3배로 제한합니다.

[desired_force]
factor = 1  # 원하는 힘의 가중치를 0.5로 설정하여 에이전트의 목표 지점으로의 이동 강도를 조절합니다.
goal_threshold = 0.2  # 목표 지점에 도달했다고 간주하는 거리 임계값을 0.2m로 설정합니다.
relaxation_time = 1.0  # 에이전트가 원하는 속도에 도달하는 데 걸리는 시간을 1.0초로 설정합니다.

[social_force]
factor = 2.5  # 사회적 힘의 가중치를 설정하여 에이전트 간의 상호작용 강도를 조절합니다.
lambda_importance = 0.8  # 위치 벡터 대비 속도 벡터의 상대적 중요도를 2.0으로 설정하여 에이전트의 회피 행동을 조절합니다.
gamma = 0.5  # 속도 상호작용을 위한 감쇠 계수를 0.35로 설정합니다.
n = 2  # 사회적 힘 계산 시 거리에 대한 지수 n을 2로 설정합니다.
n_prime = 3  # 각도에 따른 상호작용 계산 시 지수 n'을 3으로 설정합니다.

[obstacle_force]
factor = 3.0  # 장애물 힘의 가중치를 10.0으로 설정하여 에이전트와 장애물 간의 상호작용 강도를 조절합니다.
sigma = 0.2  # 장애물 힘의 표준 편차를 0.2로 설정하여 장애물 주변에서의 힘 분포를 결정합니다.
threshold = 1.0  # 장애물 힘이 작용하기 시작하는 거리 임계값을 3.0m로 설정합니다.

[group_coherence_force]
factor = 10.0  # 그룹 응집력의 가중치를 10000.0으로 설정하여 그룹 구성원들이 서로 밀착하도록 강하게 유도합니다.
threshold = 0.005  # 그룹 응집력이 작용하기 시작하는 거리 임계값을 0.1m로 설정하여 0.1m 이상 떨어지면 응집력이 작용하도록 합니다.

[group_repulsive_force]
factor = 0.2  # 그룹 내 반발력의 가중치를 0.2로 설정하여 구성원들이 지나치게 밀집되지 않도록 합니다.
threshold = 0.005  # 그룹 반발력이 작용하기 시작하는 거리 임계값을 1.0m로 설정하여 1.0m 이내로 가까워지면 반발력이 발생하도록 합니다.

[group_gaze_force]
factor = 2.0  # 그룹 시선 정렬 힘의 가중치를 2.0으로 설정하여 구성원들이 동일한 방향을 바라보도록 유도합니다.
fov_phi = 120.0  # 시야각을 120도로 설정하여 에이전트가 앞쪽 120도 범위 내의 다른 에이전트를 인식하도록 합니다.
