title = "Social Force Model Config"

[scene]
enable_group = true  
agent_radius = 1.0  
max_speed_multiplier = 1.3  

[desired_force]
factor = 0.7  
goal_threshold = 0.1  
relaxation_time = 1.5  

[social_force]
factor = 5.0  
lambda_importance = 1.0  
gamma = 0.3  
n = 2  
n_prime = 3  

[obstacle_force]
factor = 5.0  
sigma = 0.2  
threshold = 0.5  

[group_coherence_force]
factor = 10.0  
threshold = 0.01  

[group_repulsive_force]
factor = 0.5  
threshold = 0.005  

[group_gaze_force]
factor = 2.0  
fov_phi = 120.0  
